# Specify base image:
FROM ubuntu:22.04

# Copy ``ansys_inc`` directory:
COPY ansys_inc /ansys_inc

# Install dependencies (Ansys):
RUN apt -y update && apt -y install \
    csh             \
    fontconfig      \
    libxi-dev       \
    libsm6          \
    libice-dev      \
    libxrandr-dev   \
    libxinerama-dev \
    libxcursor-dev  \
    libglu1-mesa    \
    libglvnd-dev
    
# Install dependencies (Python):
RUN apt -y update && apt -y install \
    python3             \
    python3-pip         \
    python3-venv        \
    python3-setuptools

# Clean apt:
RUN apt -y autoremove && apt clean all

# User variables
# ARG USERNAME=fluent
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# Create the user
# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

# Add metadata
# LABEL description="Ansys Fluent 2024 R2"
# LABEL email="pyansys.core@ansys.com"

# OCI label
# LABEL org.opencontainers.image.documentation="https://fluent.docs.pyansys.com"

# Specify working directory
# ENV WORKING_DIRECTORY=/home/$USERNAME/$WORKING_DIRECTORY

# Specify home directory
# ENV HOME=/home/$USERNAME

# Add a working directory and make it accessible to any user
# RUN mkdir -p $WORKING_DIRECTORY \
#     && \
#     chown -R $USERNAME:$USERNAME $WORKING_DIRECTORY \
#     && \
#     chmod a+rwx $WORKING_DIRECTORY

# Set the user
# USER $USERNAME

# Set working directory
# WORKDIR /home/$USERNAME/$WORKING_DIRECTORY

# Specify default Fluent executable
# ENTRYPOINT ["/ansys_inc/v242/fluent/bin/fluent"]

# Start from shell
CMD ["/bin/bash"]
