# Build with (requires Majordome containerize tool):
# > containerize ollama-devel --container docker --no-dump
#
# Run with docker:
# > docker run -it --gpus all ollama-devel:latest bash
#
# Or with podman (if NVidia container toolkit is installed, only possible
# with a native Linux installation, not WSL):
# > podman build --build-arg OLLAMA_MODEL=codellama:13b -t ollama-devel:latest .
# > podman run -it --gpus all ollama-devel:latest

###############################################################################
# BASE IMAGE
###############################################################################

# Run `nvidia-smi` to check for GPU availability and version; you need the base
# image to match your GPU drivers. A list of supported tags is available at:
# https://hub.docker.com/r/nvidia/cuda
# ARG IMAGE=docker.io/nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04
ARG IMAGE=docker.io/nvidia/cuda:13.1.0-runtime-ubuntu24.04
FROM ${IMAGE}

# If the image build breaks (stops installing some of the packages), then it
# may be that the database needs to be updated first; place the failing command
# just after a(nother) copy of the following line:
RUN apt-get update

###############################################################################
# PYTHON SETUP
###############################################################################

# Install Python and venv tools:
RUN apt-get install -y python3 python3-venv python3-pip python3-dev

# Create a virtual environment:
RUN python3 -m venv /opt/venv

# Activate venv by using its binaries directly:
ENV PATH="/opt/venv/bin:$PATH"

# Ensure pip is up to date:
RUN python3 -m pip install --upgrade pip

###############################################################################
# PYTHON PACKAGES
###############################################################################

RUN pip install \
    'ollama>=0.6.1' \
    'haystack-ai>=2.22.0' \
    'weaviate-client[agents]>=4.19.2'

###############################################################################
# OLLAMA
###############################################################################

# Install curl for pulling ollama install script:
RUN apt-get install -y curl zstd

# Install Ollama:
RUN curl -fsSL https://ollama.com/install.sh | sh

# Pull the specified model (start server, wait, pull, then stop):
ARG OLLAMA_MODEL=ministral-3:3b
RUN ollama serve & \
    sleep 5 && \
    ollama pull ${OLLAMA_MODEL} && \
    pkill ollama

###############################################################################
# REDUCE IMAGE SIZE
###############################################################################

# Clean up and make image smaller:
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/tmp/build*

# Start script to run ollama serve in background
ENV OLLAMA_MODEL=${OLLAMA_MODEL}
CMD ["sh", "-c", "ollama serve & sleep 5 && ollama run ${OLLAMA_MODEL}"]

###############################################################################
# EOF
###############################################################################