#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

initDir="0.000000e+00"

meshFile="mesh.msh"
meshBasic="constant/polyMesh/"
meshSolid="constant/solid/polyMesh/"
meshFluid="constant/fluid/polyMesh/"

function cleanAll {
    rm -rf log.*
    rm -rf processor*
    rm -rf "${meshBasic}"
    rm -rf "${meshSolid}"
    rm -rf "${meshFluid}"
    rm -rf "constant/cellToRegion"
    rm -rf "${initDir}/cellToRegion"
    rm -rf "${initDir}/fluid/cellToRegion"
    rm -rf "${initDir}/solid/cellToRegion"
}

function privatePatches {
    foamDictionary constant/solid/polyMesh/boundary \
        -entry entry0/solidBottom/type \
        -set wall

    foamDictionary constant/solid/polyMesh/boundary \
        -entry entry0/solidTop/type \
        -set wall

    foamDictionary constant/solid/polyMesh/boundary \
        -entry entry0/solidSymmetry/type \
        -set wall

    foamDictionary constant/solid/polyMesh/boundary \
        -entry entry0/wedgeSolid/type \
        -set cyclic

    foamDictionary constant/fluid/polyMesh/boundary \
        -entry entry0/wedgeFluid/type \
        -set cyclic
}

function privateConvertMesh {
    if [ ! -d "${meshBasic}" ]; then
        gmshToFoam "${meshFile}" > log.1.gmshToFoam 2>&1
        renumberMesh > log.2.renumberMesh 2>&1
    fi

    splitMeshRegions -cellZones > log.3.splitMeshRegions 2>&1
    # rm -rf "${meshBasic}"

    privatePatches

    checkMesh -region fluid > log.4.checkMeshFluid 2>&1
    checkMesh -region solid > log.5.checkMeshSolid 2>&1
}

function ensureMesh {
    if [ ! -f "${meshFile}" ]; then
        echo "First generating the mesh with gmsh"
        exit 1
    fi

    if [ ! -d "${meshSolid}" ] || [ ! -d "${meshFluid}" ]; then
        privateConvertMesh
    fi
}

cleanAll
ensureMesh

# decomposePar -allRegions  > log.6.decomposePar 2>&1
# runParallel foamMultiRun
# runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
