[project]
name = "wsgglib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Walter Dal'Maz Silva", email = "walter.dalmazsilva@gmail.com" },
]
requires-python = ">=3.12"
dependencies = ["numpy>=2.4.6"]

[project.optional-dependencies]
full = [
    "gmsh>=4.15.2",
    "ipython>=9.13.0",
    "matplotlib>=3.10.9",
    "ruamel-yaml>=0.19.1",
]

[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
managed = true
