---
title: Thermocline model
author: Walter Dal'Maz Silva
date: last-modified
toc: true
toc-depth: 2
format:
  pdf:
    highlight-style: github
    documentclass: scrartcl
    papersize: a4
    fontsize: 11pt
    mainfont: Latin Modern Sans
    sansfont: Latin Modern Sans
    geometry:
      - margin=20mm
bibliography: https://raw.githubusercontent.com/wallytutor/kompanion/refs/heads/main/notes/references.bib
execute:
  cache: false
  echo: false
  warning: false
jupyter: python3
---

```{python}
try:
    ip = get_ipython()
    if "majordome.magic" not in ip.extension_manager.loaded:
        ip.run_line_magic('load_ext', 'majordome.magic')
except:
    pass

import thermocline as tc
import numpy as np
import sympy as sp
import yaml
```

```{=latex}
\newpage
```

# Regenerative heat exchanger model

In this section we present a simple model for the dimensioning of a thermocline energy storage system similar to a [regenerative heat exchanger](https://en.wikipedia.org/wiki/Regenerative_heat_exchanger). It is based on the use of hexagonal cells with circular holes as the solid matrix for the thermocline. The use of hexagonal cells allows for a high packing density and a large surface area for heat transfer; the calculation of the surface-to-volume ratio for this geometry is straightforward and presented in the end. It also includes the estimation of the number of cells in the cross section, thus the system diameter for a given total height and stored energy.

Other parameters relevant to the setup of a CFD simulation of the system are also estimated, such as the power per cell, the fluid injection velocity through the holes, and the associated Reynolds number. The model also includes a simple estimation of the pressure drop over the height, which is important for the design of the fluid injection system.

Below we present a summary of the parameters considered for the dimensioning of the system.

```{python}
tc.SymbolicTracker.clear()

thermocline = tc.ThermoclineDescription()
cell_block  = tc.HexagonalCell()
solid       = tc.SolidMaterial()
fluid       = tc.OperatingFluid()

S_V = cell_block.surface_to_volume_ratio
A_t = tc.total_cross_sectional_area(solid, thermocline)
N_c = tc.cells_per_cross_section(A_t, cell_block)
P_c = tc.power_per_cell(thermocline, N_c, mode="charging")
U_g = tc.fluid_injection_velocity(P_c, fluid, cell_block)
Re  = tc.reynolds_number(U_g, cell_block, fluid)

fn_S_V = tc.SymbolicTracker.lambdify(S_V)
fn_A_t = tc.SymbolicTracker.lambdify(A_t)
fn_N_c = tc.SymbolicTracker.lambdify(N_c)
fn_P_c = tc.SymbolicTracker.lambdify(P_c)
fn_U_g = tc.SymbolicTracker.lambdify(U_g)
fn_Re  = tc.SymbolicTracker.lambdify(Re)

# tc.SymbolicTracker.SYMBOLS

# ---------------------------------------------------------------------

MW = 1e6
MWh = 3600 * MW

with open("dimensioning.yaml", "r") as f:
    parameters = yaml.safe_load(f)

    num_h_t   = parameters["h_t"]
    num_H_t   = parameters["H_t"] * MWh
    num_P_c   = parameters["P_c"] * MW
    num_P_d   = parameters["P_d"] * MW
    num_T_h   = parameters["T_h"]
    num_T_c   = parameters["T_c"]
    num_m_h   = parameters["m_h"]
    num_D_h   = parameters["D_h"]
    num_rho_s = parameters["rho_s"]
    num_c_ps  = parameters["c_ps"]
    num_k_s   = parameters["k_s"]

# ---------------------------------------------------------------------

num_rho_g_c, num_h_g_c, num_mu_g_c = tc.air_properties(num_T_c)
num_rho_g_h, num_h_g_h, num_mu_g_h = tc.air_properties(num_T_h)

# ---------------------------------------------------------------------

args = [
    # ThermoclineDescription
    num_H_t,
    num_P_c,
    num_P_d,
    num_h_t,
    num_T_h,
    num_T_c,
    # HexagonalCell
    num_D_h,
    num_m_h,
    # SolidMaterial
    num_rho_s,
    num_c_ps,
    num_k_s,
    # OperatingFluid
    num_h_g_c,
    num_h_g_h,
    num_rho_g_h,  #XXX: change if charging/discharging
    num_mu_g_h,   #XXX: change if charging/discharging
]

# ---------------------------------------------------------------------

D_system = np.sqrt(4 * fn_A_t(*args) / np.pi)

# Assume 0.005 as a representative value for the relative roughness of
# refractory bricks, which have typical relative roughness in the range
# from 0.001 to 0.01. The friction factor can be estimated using the
# Swamee-Jain approximation, a simplified version of the implicit
# Colebrook-White equation given by:
# f = \dfrac{0.25}{\left[
# \log_{10}\left(\dfrac{\epsilon}{3.7D} + \dfrac{5.74}{Re^{0.9}}\right)
# \right]^2}

rho = num_rho_g_h
v = fn_U_g(*args)

# XXX check use, too high for transitional flow!
# f = tc.swamee_jain_friction_factor(fn_Re(*args), 0.008, num_D_h)

# m, absolute roughness of the hole wall
eps = 0.0002

# relative roughness of the hole wall
rel = eps / num_D_h

f = 0.05
dp = tc.darcy_weisbach_pressure_drop(L=num_h_t, D=num_D_h, rho=rho, v=v, f=f)
```

```{python}
%%md
| Parameter | Value | Units |
| --- | --- | --- |
Stored energy in thermocline                | {num_H_t/MWh:.1f}    | MWh
Target nominal operating power (charge)     | {num_P_c/MW:.1f}     | MW
Target nominal operating power (discharge)  | {num_P_d/MW:.1f}     | MW
Height of thermocline                       | {num_h_t:.1f}        | m
Diameter of system                          | {D_system:.1f}       | m
Hot working temperature                     | {num_T_h:.1f}        | K
Cold working temperature                    | {num_T_c:.1f}        | K
Diameter of holes in hexagonal cell         | {num_D_h*100:.1f}    | cm
Wall thickness scaling factor               | {num_m_h:.1f} | -
Density of solid material                   | {num_rho_s:.0f}      | kg/m³
Specific heat capacity of solid material    | {num_c_ps:.1f}       | J/kg-K
Thermal conductivity of solid material      | {num_k_s:.1f}        | W/m-K
Enthalpy of cold fluid                      | {num_h_g_c/1e6:.3f}  | MJ/kg
Enthalpy of hot fluid                       | {num_h_g_h/1e6:.3f}  | MJ/kg
Density of operating fluid (cold)           | {num_rho_g_c:.2f}    | kg/m³
Density of operating fluid (hot)            | {num_rho_g_h:.2f}    | kg/m³
Dynamic viscosity of operating fluid        | {num_mu_g_h*1e6:.2f} | uPa-s
Surface-to-volume ratio of hexagonal cell   | {fn_S_V(*args):.3f}  | 1/m
```

```{python}
%%md
The total cross-sectional area of solid material in the thermocline is given by:

$$
A_t = {sp.latex(A_t.simplify()):s}
\approx {fn_A_t(*args):.3f}\:\mathrm{m^2}
$$

what requires a system diameter of {D_system:.1f} m for the considered cell geometry and parameters. Dividing this by the cross-sectional area of solid material in each hexagonal cell gives the number of cells per cross section, which allows for calculating the power per unit cell:

$$
P_c = {sp.latex(P_c.simplify()):s}
\approx {fn_P_c(*args):.0f}\:\mathrm{W/cell}
$$

That is equivalent to saying that there should be a total of:

$$
N_c = {sp.latex(N_c.simplify()):s}
\approx {fn_N_c(*args):.0f}\:\mathrm{cells}
$$

The fluid injection velocity through the holes in the hexagonal cell is given by:

$$
U_g = {sp.latex(U_g.simplify()):s}
\approx {fn_U_g(*args):.1f}\:\mathrm{m\,s^{-1}}
$$

That allows for calculating the Reynolds number for fluid flow through the holes in the hexagonal cell:

$$
Re = {sp.latex(Re.simplify()):s}
\approx {fn_Re(*args):.0f}
$$

Assuming a roughness of {eps*1000:.1f} mm, thus a relative roughness of {rel:.3f} for the considered hole diameter. Pressure drop can be estimated using the Darcy-Weisbach equation to be in the order of {dp/100:.0f} mbar.

With the considered cell geometry, the surface-to-volume ratio of the hexagonal cell is given by:

$$
S_V = {sp.latex(S_V.simplify()):s}
\approx {fn_S_V(*args):.3f}\:\mathrm{m^{-1}}
$$

Below we display the surface-to-volume ratio of the hexagonal cell as a function of the diameter of holes and the fraction of diameter representing wall thickness.
```

```{python}
#| fig-cap: Surface-to-volume ratio of the hexagonal cell
#| fig-align: center
#| out-width: 80%
p = tc.plot_surface_to_volume_ratio(cell_block)
```

```{=latex}
\newpage
```

# Porous media model

In what follows, this note compiles a few elements on the modeling of heat transfer in packed beds. It focuses on classical implementations that can be simultaneously used in systems design that are also available in typical CFD software packages. Most of the elements compiled here are also discussed by [@Gidaspow1994] and [@Bird2001].

## Pressure drop

Early studies on pressure drop across packed columns have been performed by [@Ergun1952]; the final form equation is presented below, where the first term represents the viscous losses while the second includes kinetic energy (turbulence) effects.

$$
\dfrac{\Delta{}P}{L}g_c=%
150\dfrac{(1-\epsilon)^2}{\epsilon^3}\dfrac{\mu{}U_m}{D_p^2}+%
1.75\dfrac{(1-\epsilon)}{\epsilon^3}\dfrac{G{}U_m}{D_p}
$$

For ease of numerical implementation the following format is more convenient:

$$
\dfrac{\Delta{}P}{L}g_c=%
\dfrac{U_m}{D_p}\dfrac{(1-\epsilon)}{\epsilon^3}
\left[\dfrac{150\mu(1-\epsilon)}{D_p}+1.75G\right]
$$

where $G=\rho{}U_m$ represents the mass flow rate, $D_p$ the characteristic dimension (which can be estimated from the specific surface $S_v$ for spheres as $D_p=6S_v^{-1}$), $\epsilon$ is the fractional void volume (porosity) of the bed, $\mu$ is the fluid absolute viscosity, and $U_m$ the superficial fluid velocity measured at average pressure. This equation is interesting because it covers both the Blake-Kozeny and Burke-Plummer validity ranges.

Although the author rigorously treats the empirical data, he leaves little explanation regarding its practical use; hopefully [@Gidaspow1994] (section 2.3) reintroduces the above formulation complemented by later advances leading to

$$
\dfrac{\Delta{}P}{L}=%
150\dfrac{(1-\epsilon)^2}{\epsilon^3}\dfrac{\mu_g{}U_0}{(\phi_s{}d_p)^2}+%
1.75\dfrac{(1-\epsilon)}{\epsilon^3}\dfrac{\rho_g{}U_0^2}{\phi_s{}d_p}
$$

where the surface velocity is computed from the mean relative velocity as $U_0=\epsilon{}U$ and $\phi_s$ is the sphericity of the solid particles. Further clarifications can be found in [@Bird2001] (section 6.4).

Naturally, for non isotherm systems it is necessary to treat the problem numerically as the velocity will rely on the state-equation chosen to represent the gas phase.

## Heat transfer coefficient

In the case of on convective heat transfer coefficient determination, the classical work by [@Gunn1978] is often used as a starting point for both packed and fluidized beds. It deals mostly with the dependency of Nusselt group on Reynolds group for granular media. The recommended relationship covering a broad range of conditions is:

$$
\mathcal{Nu}=\dfrac{hd}{\lambda}=%
(7-10e+5e^2)(1+0.7\mathcal{Re}^{0.2}\mathcal{Pr}^{1/3}) +%
(1.33-2.4e+1.2e^2)\mathcal{Re}^{0.7}\mathcal{Pr}^{1/3}
$$

where $e$ denotes the porosity of the bed and the characteristic length used in Reynolds group $\mathcal{Re}$ is also particle diameter $d$, similarly to Nusselt group definition. For calculation of the heat transfer coefficient the following set of expressions is simpler to implement:

$$
\begin{aligned}
h &= \dfrac{\lambda}{d}\left[
p_1+(0.7p_1\mathcal{Re}^{-0.5}+p_2)\mathcal{Re}^{0.7}\mathcal{Pr}^{1/3}
\right]\\[6pt]
%
p_1 &= 7-10e+5e^2\\[6pt]
p_2 &= 1.33-2.4e+1.2e^2
\end{aligned}
$$

Alternatively, [@Bird2001] (section 14.5) provides

$$
\begin{aligned}
h &= c_pG_0\left(\dfrac{c_p\mu}{k}\right)^{-2/3}\left[
    2.19\mathcal{Re}^{-2/3}+0.78\mathcal{Re}^{-0.381}
    \right]\\[6pt]
\mathcal{Re} &= \dfrac{D_pG_0}{(1-\epsilon)\mu\psi}=\dfrac{6G_0}{d_p\mu\psi}
\end{aligned}
$$

where properties are evaluated at film temperature, $G_0=wS^{-1}$ is the superficial mass flux (with $w$ the mass flow rate and $S$ the column empty cross-section); $\psi$ is a particle-shape factor with defined value 1 for spheres and fitted to 0.92 for cylindrical pellets.

```{=latex}
\newpage
```

# References {.unnumbered}

::: {#refs}
:::