# Build/run with:
# containerize science-devel --container podman --no-dump
# podman run -it --gpus all -v $(realpath $PWD):/opt/app science-devel:latest bash

# ############################################################################
#  BASE IMAGE
# ############################################################################

# Run `nvidia-smi` to check for GPU availability and version; you need the base
# image to match your GPU drivers. A list of supported tags is available at:
# https://hub.docker.com/r/nvidia/cuda
# ARG IMAGE=docker.io/nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04
ARG IMAGE=docker.io/nvidia/cuda:13.1.0-runtime-ubuntu24.04
FROM ${IMAGE}

# If the image build breaks (stops installing some of the packages), then it
# may be that the database needs to be updated first; place the failing command
# just after a(nother) copy of the following line:
RUN apt-get update

# ----------------------------------------------------------------------------
# Basics and avoid locale issues
# ----------------------------------------------------------------------------

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y locales && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8     \
    LANGUAGE=en_US:en    \
    LC_CTYPE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN update-locale LANG=en_US.UTF-8

# ----------------------------------------------------------------------------
# APT installed tools
# ----------------------------------------------------------------------------

# Base development toolkit:
RUN apt-get install -y build-essential git gcc g++ gfortran make cmake

# Install curl/wget and software-properties-common for adding repositories:
RUN apt-get install -y curl wget software-properties-common

# Common libraries used in science:
RUN apt-get install -y libboost-dev liblapack-dev libopenblas-dev

# Other required software:
RUN apt-get install -y pandoc inkscape

# Other required software:
RUN apt-get install -y \
    pandoc \
    inkscape \
    texlive-full \
    poppler-utils \
    tesseract-ocr \
    imagemagick

# Linux libraries needed for PyVista/VTK:
RUN apt-get install -y \
    libxrender1 \
    libvtk9-dev \
    libosmesa6 \
    libgl1 \
    libegl1 \
    libgomp1 \
    libtbb12

# ----------------------------------------------------------------------------
# Python environment setup
# ----------------------------------------------------------------------------

# Install Python and venv tools:
RUN apt-get install -y python3 python3-venv python3-pip python3-dev

# Create a virtual environment:
RUN python3 -m venv /opt/venv

# Activate venv by using its binaries directly:
ENV PATH="/opt/venv/bin:$PATH"

# Ensure pip is up to date:
RUN python3 -m pip install --upgrade pip

# ----------------------------------------------------------------------------
# RUST
# ----------------------------------------------------------------------------

ENV CARGO_HOME=/opt/cargo
ENV RUSTUP_HOME=/opt/rustup

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path \
    --default-toolchain stable \
    --profile minimal \
    --default-host x86_64-unknown-linux-gnu

# Add Rust (Cargo actually) to PATH for all container sessions:
ENV PATH="/opt/cargo/bin:$PATH"
RUN python3 -m pip install 'maturin'

# ----------------------------------------------------------------------------
# Scientific computing packages
# ----------------------------------------------------------------------------

# Install Elmer:
RUN apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa && \
    apt-get update && apt-get install -y elmerfem-csc

# Install OpenFOAM:
RUN sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
RUN add-apt-repository http://dl.openfoam.org/ubuntu
RUN apt-get update && apt-get install -y openfoam13

# Install FEniCSx:
RUN add-apt-repository ppa:fenics-packages/fenics
RUN apt-get update && apt-get install -y fenicsx

# Install FreeFEM:
ARG FREEFEM_VERSION=4.15
ARG FREEFEM_PACKAGE=FreeFEM-${FREEFEM_VERSION}-amd64-ubuntu24.04.deb
ARG FREEFEM_REPO=https://github.com/FreeFem/FreeFem-sources

RUN cd ${APPHOME} && \
    wget ${FREEFEM_REPO}/releases/download/v${FREEFEM_VERSION}/${FREEFEM_PACKAGE} && \
    apt-get update && apt-get install -y ./${FREEFEM_PACKAGE} && \
    rm -rf ./${FREEFEM_PACKAGE}

# ----------------------------------------------------------------------------
# PRE-INSTALL
# ----------------------------------------------------------------------------

# Pre-install Python dependencies:
COPY containerfile.txt /opt/venv/containerfile.txt
RUN python3 -m pip install -r /opt/venv/containerfile.txt

# ----------------------------------------------------------------------------
# OTHER PACKAGES
# ----------------------------------------------------------------------------

ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126
RUN python3 -m pip install \
    torch torchvision torchaudio --index-url ${TORCH_INDEX_URL}

# ----------------------------------------------------------------------------
# HOME
# ----------------------------------------------------------------------------

# Set working directory:
ENV APPHOME=/opt/app
RUN mkdir -p $APPHOME
WORKDIR $APPHOME

###############################################################################
# REDUCE IMAGE SIZE
###############################################################################

# Clean up and make image smaller:
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/tmp/build*

# ############################################################################
# EOF
# ############################################################################