# Build with (requires Majordome containerize tool):
# > containerize particle-devel --container docker --no-dump
#
# Build with docker directly:
# > docker build -t particle-devel:latest -f Containerfile .
#
# Run with docker:
# > docker run --gpus all --network host particle-devel:latest

###############################################################################
# BASE IMAGE
###############################################################################

# Run `nvidia-smi` to check for GPU availability and version; you need the base
# image to match your GPU drivers. A list of supported tags is available at:
# https://hub.docker.com/r/nvidia/cuda
ARG IMAGE=docker.io/nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04
FROM ${IMAGE}

# If the image build breaks (stops installing some of the packages), then it
# may be that the database needs to be updated first; place the failing command
# just after a(nother) copy of the following line:
RUN apt-get update

# Install OpenGL libraries (required by OpenCV):
# XXX: notice that these are the same for OpenGL libraries as
# in the main scientific container for VTK/PyVista.
RUN apt-get install -y \
    libxrender1 \
    libvtk9-dev \
    libosmesa6 \
    libgl1 \
    libegl1 \
    libgomp1 \
    libtbb12

###############################################################################
# PYTHON SETUP
###############################################################################

# Install Python and venv tools:
RUN apt-get install -y python3 python3-venv python3-pip python3-dev

# Create a virtual environment:
RUN python3 -m venv /opt/venv

# Activate venv by using its binaries directly:
ENV PATH="/opt/venv/bin:$PATH"

# Ensure pip is up to date:
RUN python3 -m pip install --upgrade pip

###############################################################################
# PYTHON PACKAGES
###############################################################################

ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126
RUN pip install torch torchvision torchaudio --index-url ${TORCH_INDEX_URL}

# Just to try to accelerate ParticleAnalyzer installation:
COPY requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt

###############################################################################
# PARTICLE ANALYZER
###############################################################################

# Install git to clone ParticleAnalyzer repository:
RUN apt-get install -y git

# RUN pip install --upgrade ParticleAnalyzer
RUN git clone https://github.com/rybakov-ks/ParticleAnalyzer.git \
        /opt/ParticleAnalyzer && \
    sed -i 's/server_name="127.0.0.1"/server_name="0.0.0.0"/g' \
        /opt/ParticleAnalyzer/particleanalyzer/app.py && \
    cd /opt/ParticleAnalyzer && pip install .

# Set up configuration directory with wide permissions otherwise
# ParticleAnalyzer will fail to process results.
ENV YOLO_CONFIG_DIR="/opt/YOLO"
RUN mkdir -p ${YOLO_CONFIG_DIR} && chmod 777 ${YOLO_CONFIG_DIR}

# Run application just to download models and test installation:
RUN ParticleAnalyzer -h

###############################################################################
# REDUCE IMAGE SIZE
###############################################################################

# Clean up and make image smaller:
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/tmp/build*

###############################################################################
# RUN APPLICATION
###############################################################################

EXPOSE 5000
ENTRYPOINT ["ParticleAnalyzer", "run"]
CMD ["--port", "5000"]

###############################################################################
# EOF
###############################################################################